[functions]
  directory = "./src/api/"

[[headers]]
    for = "/*"
      [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200